### ISSUE TITLE
Error: "Maximum function nesting level of '100' reached, aborting!"

### ISSUE THREAD

**Issue by tricki** [Laralum/Laralum#7]
I followed the docs to install Laralum and get this error on the dashboard (`/administration/dashboard`).

Here is the full stack trace:

```
[2017-04-24 10:40:20] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in /laralum/vendor/laravel/framework/src/Illuminate/Support/Str.php:69
Stack trace:
#0 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php(266): Illuminate\Database\Query\Grammars\MySqlGrammar->isJsonSelector()
#4 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(99): Illuminate\Database\Query\Grammars\MySqlGrammar->wrapValue()
#5 /laralum/vendor/laravel/framework/src/Illuminate/Support/Collection.php(702): Illuminate\Database\Grammar->Illuminate\Database\{closure}()
#6 /laralum/vendor/laravel/framework/src/Illuminate/Support/Collection.php(702): array_map()
#7 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(100): Illuminate\Support\Collection->map()
#8 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(62): Illuminate\Database\Grammar->wrapSegments()
#9 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(36): Illuminate\Database\Grammar->wrap()
#10 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(98): Illuminate\Database\Grammar->wrapTable()
#11 /laralum/vendor/laravel/framework/src/Illuminate/Support/Collection.php(702): Illuminate\Database\Grammar->Illuminate\Database\{closure}()
#12 /laralum/vendor/laravel/framework/src/Illuminate/Support/Collection.php(702): array_map()
#13 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(100): Illuminate\Support\Collection->map()
#14 /laralum/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(62): Illuminate\Database\Grammar->wrapSegments()
#15 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(237): Illuminate\Database\Grammar->wrap()
#16 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(196): Illuminate\Database\Query\Grammars\Grammar->whereBasic()
#17 /laralum/vendor/laravel/framework/src/Illuminate/Support/Collection.php(702): Illuminate\Database\Query\Grammars\Grammar->Illuminate\Database\Query\Grammars\{closure}()
#18 /laralum/vendor/laravel/framework/src/Illuminate/Support/Collection.php(702): array_map()
#19 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(197): Illuminate\Support\Collection->map()
#20 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(180): Illuminate\Database\Query\Grammars\Grammar->compileWheresToArray()
#21 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(85): Illuminate\Database\Query\Grammars\Grammar->compileWheres()
#22 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(60): Illuminate\Database\Query\Grammars\Grammar->compileComponents()
#23 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php(38): Illuminate\Database\Query\Grammars\Grammar->compileSelect()
#24 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1652): Illuminate\Database\Query\Grammars\MySqlGrammar->compileSelect()
#25 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1709): Illuminate\Database\Query\Builder->toSql()
#26 /laralum/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1694): Illuminate\Database\Query\Builder->runSelect()
#27 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(452): Illuminate\Database\Query\Builder->get()
#28 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(436): Illuminate\Database\Eloquent\Builder->getModels()
#29 /laralum/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(71): Illuminate\Database\Eloquent\Builder->get()
#30 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(262): Illuminate\Database\Eloquent\Builder->first()
#31 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(292): Illuminate\Database\Eloquent\Builder->find()
#32 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1332): Illuminate\Database\Eloquent\Builder->findOrFail()
#33 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1344): Illuminate\Database\Eloquent\Model->__call()
#34 /laralum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1344): Laralum\Users\Models\User->findOrFail()
#35 /laralum/vendor/laralum/notifications/src/Injectors/user.php(7): Illuminate\Database\Eloquent\Model::__callStatic()
#36 /laralum/vendor/laralum/notifications/src/Injectors/user.php(7): Laralum\Users\Models\User::findOrFail()
#37 /laralum/vendor/laralum/laralum/src/Injector.php(38): ()
#38 /laralum/storage/framework/views/257f745c12f0b02ce38c1a8a6cd6ec003d945594.php(74): Laralum\Laralum\Injector::inject()
#39 /laralum/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): ()
#40 /laralum/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#41 /laralum/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\View\Engines\CompilerEngine->get()
#42 /laralum/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#43 /laralum/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#44 /laralum/storage/framework/views/fe4f912709080b743185d286cb839a51b96f8eda.php(39): Illuminate\View\View->render()
#45 /laralum/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): ()
#46 /laralum/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#47 /laralum/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\View\Engines\CompilerEngine->get()
#48 /laralum/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#49 /laralum/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#50 /laralum/vendor/laravel/framework/src/Illuminate/Http/Response.php(38): Illuminate\View\View->render()
#51 /laralum/vendor/symfony/http-foundation/Response.php(225): Illuminate\Http\Response->setContent()
#52 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Symfony\Component\HttpFoundation\Response->__construct()
#53 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Router.php(560): Illuminate\Routing\Router->prepareResponse()
#54 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#55 /laralum/vendor/laralum/laralum/src/Middleware/LaralumAuth.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#56 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Laralum\Laralum\Middleware\LaralumAuth->handle()
#57 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /laralum/vendor/laralum/laralum/src/Middleware/LaralumBase.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#59 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Laralum\Laralum\Middleware\LaralumBase->handle()
#60 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#62 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#63 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#65 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#66 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 /laralum/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#68 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#69 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 /laralum/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#71 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle()
#72 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#73 /laralum/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#74 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#75 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#76 /laralum/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#77 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#78 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#79 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#80 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then()
#81 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack()
#82 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute()
#83 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch()
#84 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#85 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#86 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#87 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#88 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#89 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#90 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#91 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#92 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#93 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#94 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#95 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#96 /laralum/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#97 /laralum/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#98 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then()
#99 /laralum/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#100 /laralum/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#101 /laralum/public/index.php(0): {main}()
#102 {main}

```

**Comment by 24aitor** [comment]
Can you give more information? What is your php version? Where does this error occur?

**Comment by tricki** [comment]
This is my current test setup:

PHP Version: 5.6.21
Laravel Version: 5.4
Windows 10, Xampp

I created a fresh laravel install and added a seeder for a demo user. Then I completed the installation by following the docs and opened `mysite/administrator`. After a login I was redirected to `mysite/administrator/dashboard` and saw this (after opening the "Admin" dropdown):

![image](https://cloud.githubusercontent.com/assets/523154/25341588/982c1632-2909-11e7-81c4-251c6d54bdf1.png)

Let me know if you need any more information.

**Comment by 24aitor** [comment]
Well, this problem is not from laralum, take a look to this link http://stackoverflow.com/questions/17488505/php-error-maximum-function-nesting-level-of-100-reached-aborting

**Comment by webmake** [comment]
Since
#44 /laralum/storage/framework/views/fe4f912709080b743185d286cb839a51b96f8eda.php(39): this one I see call to database:
#36 /laralum/vendor/laralum/notifications/src/Injectors/user.php(7): Laralum\Users\Models\User::findOrFail()
This should be done before passing to view. View must be only responsible for data representation, not bussiness logic.

**Comment by webmake** [comment]
`$user = \Laralum\Users\Models\User::findOrFail(Auth::id());`
more over once again call find
`{{ Laralum\Users\Models\User::findOrFail(Auth::id())->avatar() }}`
in [file](https://github.com/Laralum/Laralum/blob/master/src/Views/layouts/master.blade.php)
might cause issue. Please author move it to controller.

increasing xdebug.max_nesting_level ini is not a solution, but workaround.

**Comment by ConsoleTVs** [comment]
I never used xdebug and I don't know what it really does.

In any case, what do you mean "moving it to a controller" ? It's a template, you don't want to pass everything needed in each view you show...

**Comment by webmake** [comment]
xdebug.max_nesting_level it's default php environment [config](http://php.net/manual/en/ini.list.php), it means that call depth is too high, and complexity is too high. So imagine function call map ![map](https://i.stack.imgur.com/3xXmg.png)
it's a huge net if would need 100...

So, returning to the problem, template must not call database at all, it's design pattern violation. Template must have prepared values to render, which are passed from controller, otherwise it should deal like nothing given (nullable values).

In generally, route is associated with controller action or anonymous function, action renders specific view, (there shouldn't be anonymous functions, because it causes cache problem, it's a laravel bug if no one fixed it yet). So I don't see any problem to extract all fetches like `\Laralum\Users\Models\User::findOrFail` to action method, now it's even duplicated code in view and could be done only once..
If there isn't one controller method dealing with same view, then yes, should be included fecthing data in each action, so you reuse methods only (keep DRY pattern) over there.

You have to provide ability to extend view/controller, but not do everything where it need, as done from view now.

**Comment by ConsoleTVs** [comment]
So you're telling me {{ Auth::user()->name }} is wrong and should be passed from the view? hell no!

We have +100 views, and that includes +100 functions that call them, they all end up loading the same layout so you're telling me to pass a user parammeter on EACH one? Sounds stupid to me...

**Comment by webmake** [comment]
No, `\Laralum\Users\Models\User::findOrFail` is wrong, I said nothing about Auth::user(), this is not causing issues at all, because auth is laravel functionality, and fetches before it passed to template.
https://github.com/Laralum/Laralum/blob/master/src/Views/layouts/master.blade.php#L4
https://github.com/Laralum/Laralum/blob/master/src/Views/layouts/master.blade.php#L115

**Comment by ConsoleTVs** [comment]
So your optimitzation requires passing all database models to the view? Not much sense, as I said there are 100s of views that needs this data.

**Comment by webmake** [comment]
Exactly.
Then wrong achitecture, that code is not reusable and need to change all 100s templates (later i will check how much places exist). It should be one place to change but now it became "impossible" for no reason.
How about view parameter share (at least)? :
```
$id = Auth::id();
$user = \Laralum\Users\Models\User::findOrFail($id);
view()->share('user', $user);
```

**Comment by ConsoleTVs** [comment]
There are no 100 files to be changed, only the layout. If we use view share in the service provider to use it across the panel, it will also be available in the front end, returning a 1-0 win, not a 1-1 win. This will probably use more resources... We will study the situation but I honestly think there's not much of an improvement in changing this.
